type CombinationAttributeName =
    | 'Abilities'
    | 'Abiltities.ability'
    | 'Abilities.source'
    | 'Air Speed'
    | 'Animal 1'
    | 'Animal 2'
    | 'Coal'
    | 'Defence'
    | 'EHP'
    | 'Electricity'
    | 'Front Legs'
    | 'Head'
    | 'Health'
    | 'Land Speed'
    | 'Melee Damage'
    | 'Pincers'
    | 'Population Size'
    | 'Power'
    | 'Rear Legs'
    | 'Research Level'
    | 'SDT'
    | 'Sight Radius'
    | 'Size'
    | 'Tail'
    | 'Torso'
    | 'Water Speed'
    | 'Wings';

export default CombinationAttributeName;
