services:
  combinations-database:
    image: mongo
    ports:
      - '27017:27017'

  combinations-server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - combinations-database

  combinations-client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    depends_on:
      - combinations-database
      - combinations-server




