const abilities: Record<string, string> = {
    end_bonus: 'High Endurance',
    keen_sense: 'Keen Sense',
    herding: 'Herding',
    pack_hunter: 'Pack Hunter',
    is_stealthy: 'Camouflage',
    can_dig: 'Digging',
    can_SRF: 'Hovering',
    frenzy_attack: 'Frenzy',
    stink_attack: 'Stink Cloud',
    deflection_armour: 'Deflection Armour',
    charge_attack: 'Charge',
    leap_attack: 'Leap Attack',
    assassinate: 'Assassinate',
    poplow: 'Colony',
    poplowtorso: 'Conglomerate',
    soiled_land: 'Defile Land',
    AutoDefense: 'Disorienting Barbs',
    electric_burst: 'Electric Burst',
    flash: 'Flash',
    headflashdisplay: 'Head Flash',
    is_immune: 'Immunity',
    infestation: 'Infestation',
    loner: 'Loner',
    overpopulation: 'Overpopulation',
    plague_attack: 'Plague',
    poison_touch: 'Poison Touch',
    poison_bite: 'Poison Bite',
    poison_pincers: 'Poison Tip',
    poison_sting: 'Poison Sting',
    ranged_piercing: 'Perforate',
    quill_burst: 'Quill Burst',
    regeneration: 'Regeneration',
    sonar_pulse: 'Sonar Pulse',
    web_throw: 'Web Throw',
    imaginary_hovering: 'Imaginary Hovering',
    hard_shell: 'Hardened Shell',
}

export default abilities
