import {ModSchema} from '../types/ModSchema';
import {ModSchemaColumn} from '../types/ModSchemaColumn';
import {
    ABILITIES,
    AIR_SPEED,
    ANIMAL1,
    ANIMAL2,
    COAL,
    DEFENCE,
    EHP,
    ELECTRICITY,
    ELECTRICITY_TELLURIAN,
    FRONT_LEGS,
    GENERATED_EHP,
    HEAD,
    HEALTH,
    LAND_SPEED,
    MELEE_DAMAGE,
    PINCERS,
    POPULATION_SIZE,
    POWER,
    REAR_LEGS,
    RESEARCH_LEVEL,
    SDT,
    SIGHT_RADIUS,
    SIZE,
    TAIL,
    TORSO,
    WATER_SPEED,
    WINGS,
} from './modSchemaColumns';
import {ModNames} from '../types/ModNames';

const standardModSchema: ModSchemaColumn[] = [
    ANIMAL1,
    ANIMAL2,
    RESEARCH_LEVEL,
    COAL,
    ELECTRICITY,
    HEALTH,
    GENERATED_EHP,
    SDT,
    SIZE,
    POPULATION_SIZE,
    MELEE_DAMAGE,
    DEFENCE,
    AIR_SPEED,
    LAND_SPEED,
    WATER_SPEED,
    SIGHT_RADIUS,
    FRONT_LEGS,
    REAR_LEGS,
    HEAD,
    TAIL,
    TORSO,
    PINCERS,
    WINGS,
    ABILITIES,
];

const tellurianLegacyModColumns: ModSchemaColumn[] = [
    ANIMAL1,
    ANIMAL2,
    RESEARCH_LEVEL,
    COAL,
    ELECTRICITY,
    POWER,
    GENERATED_EHP,
    SDT,
    HEALTH,
    SIZE,
    POPULATION_SIZE,
    MELEE_DAMAGE,
    DEFENCE,
    AIR_SPEED,
    LAND_SPEED,
    WATER_SPEED,
    SIGHT_RADIUS,
    FRONT_LEGS,
    REAR_LEGS,
    HEAD,
    TAIL,
    TORSO,
    PINCERS,
    WINGS,
    ABILITIES,
];

const tellurianModSchemaColumns: ModSchemaColumn[] = [
    ANIMAL1,
    ANIMAL2,
    RESEARCH_LEVEL,
    COAL,
    ELECTRICITY_TELLURIAN,
    POWER,
    EHP,
    SDT,
    HEALTH,
    SIZE,
    POPULATION_SIZE,
    MELEE_DAMAGE,
    DEFENCE,
    AIR_SPEED,
    LAND_SPEED,
    WATER_SPEED,
    SIGHT_RADIUS,
    FRONT_LEGS,
    REAR_LEGS,
    HEAD,
    TAIL,
    TORSO,
    PINCERS,
    WINGS,
    ABILITIES,
];

const schemas: ModSchema[] = [
    {
        name: ModNames.VANILLA,
        version: '1.1',
        columns: standardModSchema,
    },
    {
        name: ModNames.INSECT_INVASION,
        version: '1.4',
        columns: standardModSchema,
    },
    {
        name: ModNames.SMOD,
        version: '9.25',
        columns: standardModSchema,
    },
    {
        name: ModNames.TELLURIAN,
        version: '2.0',
        columns: tellurianLegacyModColumns,
    },
    {
        name: ModNames.TELLURIAN,
        version: '2.9.1.4',
        columns: tellurianModSchemaColumns,
    },
    {
        name: ModNames.TELLURIAN,
        version: '2.10',
        columns: tellurianModSchemaColumns,
    },
    {
        name: ModNames.TELLURIAN,
        version: '2.10.0.3',
        columns: tellurianModSchemaColumns,
    },
];

export default schemas;
