enum CombinationAttributeDescriptions {
    ABILITIES = 'The abilities the creature has.',
    ABILITY_SOURCES = 'The limb responsible for the ability.',
    ANIMAL_1 = "The first animal in the creature's composition.",
    ANIMAL_2 = "The second animal in the creature's composition.",
    RESEARCH_LEVEL = 'The research level required to build the creature.',
    COAL = 'The coal required to build the creature.',
    ELECTRICITY = 'The electricity required to build the creature.',
    HEALTH = "The creature's health.",
    EHP = "The creature's effective hit points.",
    GENERATED_EHP = "The creature's effective hit points.",
    SDT = "The creature's self-destruction time.",
    POPULATION_SIZE = "The creature's population size.",
    MELEE_DAMAGE = "The creature's total melee damage.",
    DEFENCE = "The creature's total defence value.",
    AIR_SPEED = "The creature's air speed.",
    LAND_SPEED = "The creature's land speed.",
    WATER_SPEED = "The creature's water speed.",
    SIGHT_RADIUS = "The creature's sight radius.",
    FRONT_LEGS = "The animal from which the creature's front legs are composed.",
    REAR_LEGS = "The animal from which the creature's rear legs are composed.",
    HEAD = "The animal from which the creature's head is composed.",
    TAIL = "The animal from which the creature's tail is composed.",
    TORSO = "The animal from which the creature's torso is composed.",
    PINCERS = "The animal from which the creature's pincers are composed.",
    WINGS = "The animal from which the creature's wings are composed.",
    POWER = 'The power rating of the creature.',
    SIZE = 'The size of the creature.',
}

export default CombinationAttributeDescriptions
