import {
    ABILITIES,
    ABILITY_SOURCES,
    AIR_SPEED,
    ANIMAL1,
    ANIMAL2,
    COAL,
    DEFENCE,
    EHP,
    ELECTRICITY,
    ELECTRICITY_TELLURIAN,
    FRONT_LEGS,
    GENERATED_EHP,
    HEAD,
    HEALTH,
    LAND_SPEED,
    MELEE_DAMAGE,
    PINCERS,
    POPULATION_SIZE,
    POWER,
    REAR_LEGS,
    RESEARCH_LEVEL,
    SDT,
    SIGHT_RADIUS,
    SIZE,
    TAIL,
    TORSO,
    WATER_SPEED,
    WINGS,
} from './modSchemaColumns'
import ModSchemaColumn from '../../types/ModSchemaColumn'
import ModSchema from '../../types/ModSchema'
import ModNames from '../../types/ModNames'

export const vanillaModSchemaColumns: ModSchemaColumn[] = [
    ANIMAL1,
    ANIMAL2,
    RESEARCH_LEVEL,
    COAL,
    ELECTRICITY,
    HEALTH,
    GENERATED_EHP,
    SDT,
    SIZE,
    POPULATION_SIZE,
    MELEE_DAMAGE,
    DEFENCE,
    AIR_SPEED,
    LAND_SPEED,
    WATER_SPEED,
    SIGHT_RADIUS,
    FRONT_LEGS,
    REAR_LEGS,
    HEAD,
    TAIL,
    TORSO,
    PINCERS,
    WINGS,
    ABILITIES,
    ABILITY_SOURCES,
]

export const tellurianLegacyModSchemaColumns: ModSchemaColumn[] = [
    ANIMAL1,
    ANIMAL2,
    RESEARCH_LEVEL,
    COAL,
    ELECTRICITY,
    POWER,
    GENERATED_EHP,
    SDT,
    HEALTH,
    SIZE,
    POPULATION_SIZE,
    MELEE_DAMAGE,
    DEFENCE,
    AIR_SPEED,
    LAND_SPEED,
    WATER_SPEED,
    SIGHT_RADIUS,
    FRONT_LEGS,
    REAR_LEGS,
    HEAD,
    TAIL,
    TORSO,
    PINCERS,
    WINGS,
    ABILITIES,
    ABILITY_SOURCES,
]

export const tellurianModSchemaColumns: ModSchemaColumn[] = [
    ANIMAL1,
    ANIMAL2,
    RESEARCH_LEVEL,
    COAL,
    ELECTRICITY_TELLURIAN,
    POWER,
    EHP,
    SDT,
    HEALTH,
    SIZE,
    POPULATION_SIZE,
    MELEE_DAMAGE,
    DEFENCE,
    AIR_SPEED,
    LAND_SPEED,
    WATER_SPEED,
    SIGHT_RADIUS,
    FRONT_LEGS,
    REAR_LEGS,
    HEAD,
    TAIL,
    TORSO,
    PINCERS,
    WINGS,
    ABILITIES,
    ABILITY_SOURCES,
]

export const schemas: ModSchema[] = [
    {
        name: ModNames.VANILLA,
        version: '1.1',
        columns: vanillaModSchemaColumns,
    },
    {
        name: ModNames.INSECT_INVASION,
        version: '1.4',
        columns: vanillaModSchemaColumns,
    },
    {
        name: ModNames.SMOD,
        version: '9.25',
        columns: vanillaModSchemaColumns,
    },
    {
        name: ModNames.TELLURIAN,
        version: '2.0',
        columns: tellurianLegacyModSchemaColumns,
    },
    {
        name: ModNames.TELLURIAN,
        version: '2.9.1.4',
        columns: tellurianModSchemaColumns,
    },
    {
        name: ModNames.TELLURIAN,
        version: '2.10',
        columns: tellurianModSchemaColumns,
    },
    {
        name: ModNames.TELLURIAN,
        version: '2.10.0.3',
        columns: tellurianModSchemaColumns,
    },
]

export default schemas
