import {DEFAULT_MOD, MOD_COMBINATION_TOTALS} from '../../../src/globals'
import Combination from '../../../src/types/Combination'
import UnprocessedCombination from '../../../src/types/UnprocessedCombination'

export const testUnprocessedCombinations: UnprocessedCombination[] = [
    {
        attributes: {
            armour: [1, 0.3999999761581421],
            armour_rating: [-1, 4],
            armour_val: [-1, 40],
            buildtime: [-1, 10],
            can_dig: [2, 1],
            constructionticks: [-1, 32],
            cost: [-1, 78.66000366210938],
            costrenew: [-1, 25],
            creature_rank: [-1, 1],
            damage_rating: [-1, 3],
            damage_val: [-1, 10],
            health_rating: [-1, 1],
            health_val: [-1, 30],
            hitpoints: [1, 30],
            is_immune: [0, 1],
            is_land: [1, 1],
            land_legs_counted: [1, 2],
            landspeed_rating: [-1, 2],
            landspeed_val: [-1, 26],
            lefthalf_name: [1, 24002],
            melee2_damage: [2, 5],
            melee2_dmgtype: [2, 0],
            melee2_longdesc: [2, 5017],
            melee2_name: [2, 5015],
            melee2_rate: [2, 1.25],
            melee2_shortdesc: [2, 5016],
            melee4_damage: [4, 5],
            melee4_dmgtype: [4, 0],
            melee4_longdesc: [4, 5012],
            melee4_name: [4, 5010],
            melee4_rate: [4, 1.25],
            melee4_shortdesc: [4, 5011],
            melee_damage: [0, 10],
            popsize: [-1, 1],
            righthalf_name: [1, 24007],
            sight_radius1: [0, 20],
            sightradius_rating: [-1, 1],
            sightradius_val: [-1, 20],
            size: [1, 1],
            size_rating: [-1, 1],
            size_val: [-1, 1],
            speed_max: [0, 26],
        },
        composition: [1, 1, 1, 1, 1, 1, 1],
        stock_1: 'ant',
        stock_2: 'archerfish',
    },
    {
        attributes: {
            armour: [1, 0.06000000238418579],
            armour_rating: [-1, 1],
            armour_val: [-1, 6],
            buildtime: [-1, 10],
            constructionticks: [-1, 48],
            cost: [-1, 66.76000213623047],
            costrenew: [-1, 55],
            creature_rank: [-1, 2],
            damage_rating: [-1, 1],
            damage_val: [-1, 2],
            health_rating: [-1, 1],
            health_val: [-1, 18],
            hitpoints: [1, 18],
            is_immune: [0, 1],
            is_swimmer: [1, 1],
            lefthalf_name: [1, 24002],
            melee4_damage: [4, 2],
            melee4_dmgtype: [4, 0],
            melee4_longdesc: [4, 5002],
            melee4_name: [4, 5000],
            melee4_rate: [4, 1.25],
            melee4_shortdesc: [4, 5001],
            melee_damage: [0, 2],
            popsize: [-1, 1],
            range4_damage: [4, 3],
            range4_damage_rating: [-1, 1],
            range4_damage_val: [-1, 3],
            range4_dmgtype: [4, 0],
            range4_longdesc: [4, 5007],
            range4_max: [4, 20],
            range4_max_rating: [-1, 4],
            range4_max_val: [-1, 20],
            range4_min: [4, 7],
            range4_name: [4, 5005],
            range4_rate: [4, 1.25],
            range4_shortdesc: [4, 5006],
            range4_special: [4, 2],
            righthalf_name: [1, 24007],
            sight_radius1: [0, 30],
            sightradius_rating: [-1, 2],
            sightradius_val: [-1, 30],
            size: [1, 1],
            size_rating: [-1, 1],
            size_val: [-1, 1],
            waterspeed_max: [0, 30],
            waterspeed_rating: [-1, 4],
            waterspeed_val: [-1, 30],
        },
        composition: [2, 2, 2, 2, 2, 2, 2],
        stock_1: 'ant',
        stock_2: 'archerfish',
    },
    {
        attributes: {
            armour: [1, 0.2499999850988388],
            armour_rating: [-1, 3],
            armour_val: [-1, 25],
            buildtime: [-1, 10],
            can_dig: [2, 1],
            constructionticks: [-1, 48],
            cost: [-1, 64.62000274658203],
            costrenew: [-1, 25],
            creature_rank: [-1, 2],
            damage_rating: [-1, 3],
            damage_val: [-1, 10],
            health_rating: [-1, 1],
            health_val: [-1, 30],
            hitpoints: [1, 30],
            is_immune: [0, 1],
            is_land: [1, 1],
            is_swimmer: [1, 1],
            land_legs_counted: [1, 2],
            landspeed_rating: [-1, 1],
            landspeed_val: [-1, 20.799999237060547],
            lefthalf_name: [1, 24002],
            melee2_damage: [2, 5],
            melee2_dmgtype: [2, 0],
            melee2_longdesc: [2, 5017],
            melee2_name: [2, 5015],
            melee2_rate: [2, 1.25],
            melee2_shortdesc: [2, 5016],
            melee4_damage: [4, 5],
            melee4_dmgtype: [4, 0],
            melee4_longdesc: [4, 5012],
            melee4_name: [4, 5010],
            melee4_rate: [4, 1.25],
            melee4_shortdesc: [4, 5011],
            melee_damage: [0, 10],
            popsize: [-1, 1],
            righthalf_name: [1, 24007],
            sight_radius1: [0, 20],
            sightradius_rating: [-1, 1],
            sightradius_val: [-1, 20],
            size: [1, 1],
            size_rating: [-1, 1],
            size_val: [-1, 1],
            speed_max: [0, 20.799999237060547],
            waterspeed_max: [0, 10],
            waterspeed_rating: [-1, 4],
            waterspeed_val: [-1, 10],
        },
        composition: [1, 1, 1, 1, 2, 2, 2],
        stock_1: 'ant',
        stock_2: 'archerfish',
    },
]
export const testProcessedCombinations: Combination[] = [
    {
        Abilities: ['Digging', 'Immunity'],
        'Ability Sources': ['Head', 'Innate'],
        'Air Speed': 0,
        'Animal 1': 'Ant',
        'Animal 2': 'Archerfish',
        Coal: 78.7,
        Defence: 40,
        EHP: 50,
        Electricity: 25,
        'Front Legs': 'Ant',
        Head: 'Ant',
        Health: 30,
        'Land Speed': 26,
        'Melee Damage': 10,
        Mod: {name: DEFAULT_MOD.name, version: DEFAULT_MOD.version},
        Pincers: 'Ant',
        'Population Size': 1,
        Power: 0,
        'Rear Legs': 'Ant',
        'Research Level': 1,
        SDT: 5,
        'Sight Radius': 20,
        Size: 1,
        Tail: 'Ant',
        Torso: 'Ant',
        'Water Speed': 0,
        Wings: 'Ant',
    },
    {
        Abilities: ['Immunity'],
        'Ability Sources': ['Innate'],
        'Air Speed': 0,
        'Animal 1': 'Ant',
        'Animal 2': 'Archerfish',
        Coal: 66.8,
        Defence: 6,
        EHP: 19.1,
        Electricity: 55,
        'Front Legs': 'Archerfish',
        Head: 'Archerfish',
        Health: 18,
        'Land Speed': 0,
        'Melee Damage': 2,
        Mod: {name: DEFAULT_MOD.name, version: DEFAULT_MOD.version},
        Pincers: 'Archerfish',
        'Population Size': 1,
        Power: 0,
        'Rear Legs': 'Archerfish',
        'Research Level': 2,
        SDT: 9.6,
        'Sight Radius': 30,
        Size: 1,
        Tail: 'Archerfish',
        Torso: 'Archerfish',
        'Water Speed': 30,
        Wings: 'Archerfish',
    },
    {
        Abilities: ['Digging', 'Immunity'],
        'Ability Sources': ['Head', 'Innate'],
        'Air Speed': 0,
        'Animal 1': 'Ant',
        'Animal 2': 'Archerfish',
        Coal: 64.6,
        Defence: 25,
        EHP: 40,
        Electricity: 25,
        'Front Legs': 'Ant',
        Head: 'Ant',
        Health: 30,
        'Land Speed': 20.8,
        'Melee Damage': 10,
        Mod: {name: DEFAULT_MOD.name, version: DEFAULT_MOD.version},
        Pincers: 'Archerfish',
        'Population Size': 1,
        Power: 0,
        'Rear Legs': 'Ant',
        'Research Level': 2,
        SDT: 4,
        'Sight Radius': 20,
        Size: 1,
        Tail: 'Ant',
        Torso: 'Archerfish',
        'Water Speed': 10,
        Wings: 'Archerfish',
    },
]

export const totalNumberOfMods = MOD_COMBINATION_TOTALS.length

export const testCombination1: Combination = {
    Abilities: [],
    'Ability Sources': [],
    'Air Speed': 3,
    'Animal 1': 'testAnimal1',
    'Animal 2': 'testAnimal2',
    Coal: 10,
    Defence: 1,
    EHP: 9,
    Electricity: 100,
    'Front Legs': 'testAnimal1',
    Head: 'testAnimal2',
    Health: 6,
    'Land Speed': 4,
    'Melee Damage': 10,
    Mod: {name: DEFAULT_MOD.name, version: DEFAULT_MOD.version},
    Pincers: 'testAnimal1',
    'Population Size': 8,
    Power: 2,
    'Rear Legs': 'testAnimal1',
    'Research Level': 1,
    SDT: 1.5,
    'Sight Radius': 11,
    Size: 7,
    Tail: 'testAnimal2',
    Torso: 'testAnimal2',
    'Water Speed': 5,
    Wings: 'testAnimal1',
}

export const testCombination2: Combination = {
    Abilities: ['Digging'],
    'Ability Sources': ['Innate'],
    'Air Speed': 32,
    'Animal 1': 'testAnimal3',
    'Animal 2': 'testAnimal4',
    Coal: 20,
    Defence: 2,
    EHP: 92,
    Electricity: 200,
    'Front Legs': 'testAnimal3',
    Head: 'testAnimal3',
    Health: 62,
    'Land Speed': 42,
    'Melee Damage': 102,
    Mod: {name: DEFAULT_MOD.name, version: DEFAULT_MOD.version},
    Pincers: 'testAnimal4',
    'Population Size': 82,
    Power: 22,
    'Rear Legs': 'testAnimal4',
    'Research Level': 2,
    SDT: 2.5,
    'Sight Radius': 112,
    Size: 72,
    Tail: 'testAnimal3',
    Torso: 'testAnimal3',
    'Water Speed': 52,
    Wings: 'testAnimal4',
}

export const testCombination3: Combination = {
    Abilities: [],
    'Ability Sources': [],
    'Air Speed': 33,
    'Animal 1': 'testAnimal5',
    'Animal 2': 'testAnimal6',
    Coal: 30,
    Defence: 3,
    EHP: 93,
    Electricity: 300,
    'Front Legs': 'testAnimal5',
    Head: 'testAnimal6',
    Health: 63,
    'Land Speed': 43,
    'Melee Damage': 103,
    Mod: {name: DEFAULT_MOD.name, version: DEFAULT_MOD.version},
    Pincers: 'testAnimal5',
    'Population Size': 83,
    Power: 23,
    'Rear Legs': 'testAnimal5',
    'Research Level': 3,
    SDT: 3.5,
    'Sight Radius': 113,
    Size: 73,
    Tail: 'testAnimal6',
    Torso: 'testAnimal6',
    'Water Speed': 53,
    Wings: 'testAnimal5',
}
