name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the backend Docker image
      run: docker build . --file backend.Dockerfile --tag backend:$(date +%s)
    - name: Build The frontend Docker image
      run: docker build . --file frontend.Dockerfile --tag backend:$(date +%s)
