name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  backend-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use latest stable Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 'node'  
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install
      working-directory: backend 

    - name: Run Jest
      run: npm backend:test
      working-directory: backend
      env:
        CI: true

